instance_create_layer(765, 323,"instances", obj_ArqEnemy)
instance_create_layer(65,288,"instances", obj_player)
instance_destroy(obj_ArqEnemyCutscene)
instance_destroy(obj_playerCut59)
instance_destroy(obj_lightControl2)
instance_destroy(obj_ct2)
instance_destroy(obj_lightTrue)
instance_destroy(obj_texto60)
